<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Actions\Support\SaveSupportDocument;
use App\Http\Controllers\Controller;
use App\Http\Requests\Support\SupportDocumentRequest;
use App\Http\Resources\SupportDocumentResource;
use App\Models\KnowledgeDocument;
use App\Support\Audit\AuditLogger;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * The support policy corpus admin (PRD §6.13). Gated by `can:handle-tickets` — support
 * policy belongs to the people answering the tickets, not to curriculum.
 *
 * Until this existed the corpus was seeder-only: it could only change by deploy, which
 * made deflection quality a function of the release cycle. Deflection can only answer
 * from documents that exist, so this is the screen that decides whether the feature
 * works at all.
 *
 * Scoped to `source_type=support` throughout. The tutor's own documents (course,
 * program, lab, transcript) share the table but are machine-generated by
 * `tutor:reindex`, and editing them here would be silently undone on the next rebuild.
 */
final class SupportDocumentController extends Controller
{
    public function index(): JsonResponse
    {
        $documents = KnowledgeDocument::query()
            ->where('source_type', 'support')
            ->withCount('chunks')
            ->orderBy('category')
            ->orderBy('title')
            ->get();

        return SupportDocumentResource::collection($documents)->response();
    }

    public function store(SupportDocumentRequest $request, SaveSupportDocument $save): JsonResponse
    {
        $document = $save->handle($request->validated(), null, $request->user());

        return (new SupportDocumentResource($document->loadCount('chunks')))->response()->setStatusCode(201);
    }

    public function update(SupportDocumentRequest $request, int $document, SaveSupportDocument $save): JsonResponse
    {
        $model = $this->supportDocument($document);
        $updated = $save->handle($request->validated(), $model, $request->user());

        return (new SupportDocumentResource($updated->loadCount('chunks')))->response();
    }

    public function destroy(Request $request, int $document, AuditLogger $audit): JsonResponse
    {
        $model = $this->supportDocument($document);

        // Chunks cascade with the document, so retrieval cannot cite a deleted policy.
        $audit->log('support_document.deleted', $model, ['title' => $model->title], $request->user());
        $model->chunks()->delete();
        $model->delete();

        return response()->json(['ok' => true]);
    }

    /**
     * Tenant-scoped by the model's global scope; 404s anything that is not a support
     * document, so this endpoint can never edit or delete the tutor's corpus.
     */
    private function supportDocument(int $id): KnowledgeDocument
    {
        $document = KnowledgeDocument::query()
            ->where('source_type', 'support')
            ->find($id);

        if ($document === null) {
            throw new NotFoundHttpException;
        }

        return $document;
    }
}
