import { NextResponse } from "next/server";

/**
 * Most-frequently-asked interview questions per track, grouped by round —
 * generated by kimi-k3 (the platform LLM) and cached in-memory for an hour.
 * Powers the round-by-round question panels on the /v3 success stories.
 * Falls back to a curated bank when the key is missing or the call fails.
 */

export const revalidate = 3600;

type Round = { round: number; name: string; questions: string[] };
type Tracks = Record<string, Round[]>;
type Payload = { tracks: Tracks; source: "kimi-k3" | "sample"; updated: string };

const FALLBACK_TRACKS: Tracks = {
  "data-engineering": [
    { round: 1, name: "SQL screening", questions: ["Top 3 salaries per department — write it", "Explain window functions vs GROUP BY", "Find duplicate rows without DISTINCT"] },
    { round: 2, name: "Pipelines & Spark", questions: ["Why is your Spark job slow? Debug it", "Partitioning vs bucketing — when each?", "Design an incremental load for late data"] },
    { round: 3, name: "System design", questions: ["Design a daily 1TB ETL pipeline", "Handle schema drift in production"] },
    { round: 4, name: "Managerial", questions: ["Walk through a pipeline failure you owned", "Why data engineering after your background?"] },
  ],
  "devops-cloud": [
    { round: 1, name: "Linux & scripting", questions: ["Debug a server at 100% CPU", "Explain what happens during a kernel panic"] },
    { round: 2, name: "Containers & K8s", questions: ["Debug a CrashLoopBackOff — live", "Liveness vs readiness probes — why both?", "Multi-stage Docker builds — what and why?"] },
    { round: 3, name: "IaC & CI/CD", questions: ["Terraform state got corrupted — recover it", "Design a zero-downtime deploy"] },
    { round: 4, name: "Managerial", questions: ["Worst production incident — your role?", "How do you push back on risky releases?"] },
  ],
  "python-backend": [
    { round: 1, name: "Python core", questions: ["Explain decorators with a real use-case", "Generators vs lists — memory story"] },
    { round: 2, name: "APIs & data", questions: ["Design a rate limiter", "N+1 queries — find and fix them"] },
    { round: 3, name: "System design", questions: ["Design a URL shortener at scale", "Where do you add caching, and why there?"] },
  ],
  "data-analytics": [
    { round: 1, name: "SQL & Excel", questions: ["Running totals with window functions", "INDEX-MATCH vs VLOOKUP — when and why?"] },
    { round: 2, name: "BI & storytelling", questions: ["A DAX measure returns wrong totals — debug", "Walk us through a dashboard you built"] },
    { round: 3, name: "Case round", questions: ["Sales dropped 12% — investigate with data", "Which metric would you cut? Defend it"] },
  ],
};

let cache: Payload | null = null;
let cachedAt = 0;
const TTL_MS = 60 * 60 * 1000;

export async function GET() {
  const key = process.env.KIMI_API_KEY;
  const stamp = new Date().toISOString();
  if (!key) return NextResponse.json({ tracks: FALLBACK_TRACKS, source: "sample", updated: stamp });
  if (cache && Date.now() - cachedAt < TTL_MS) return NextResponse.json(cache);

  try {
    const res = await fetch("https://api.moonshot.ai/v1/chat/completions", {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${key}` },
      body: JSON.stringify({
        // kimi-k3: temperature must be 1; low reasoning effort keeps latency ~15s.
        model: process.env.KIMI_MODEL ?? "kimi-k3",
        temperature: 1,
        max_tokens: 6000,
        reasoning_effort: "low",
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content:
              "You are an interview-prep analyst who has read thousands of real Indian tech interview transcripts. Respond with strict JSON only.",
          },
          {
            role: "user",
            content:
              'Return {"tracks":{"data-engineering":[{"round":1,"name":"...","questions":["...","...","..."]} x4],"devops-cloud":[x4],"python-backend":[x3],"data-analytics":[x3]}}. For each track give the MOST FREQUENTLY asked real interview questions in Indian tech hiring right now, grouped by round in the usual loop order (screening -> technical deep-dive -> system design/case -> managerial). Round "name" under 4 words. Each question under 12 words, specific and realistic (e.g. "Debug a CrashLoopBackOff — live"). 2-3 questions per round.',
          },
        ],
      }),
      signal: AbortSignal.timeout(60_000),
    });
    if (!res.ok) throw new Error(`moonshot ${res.status}`);
    const body = (await res.json()) as { choices?: { message?: { content?: string } }[] };
    const parsed = JSON.parse(body.choices?.[0]?.message?.content ?? "") as { tracks: Tracks };
    const tracks = parsed.tracks;
    if (!tracks || !Array.isArray(tracks["data-engineering"]) || tracks["data-engineering"].length === 0) {
      throw new Error("bad shape");
    }
    cache = { tracks, source: "kimi-k3", updated: stamp };
    cachedAt = Date.now();
    return NextResponse.json(cache);
  } catch {
    return NextResponse.json({ tracks: FALLBACK_TRACKS, source: "sample", updated: stamp });
  }
}
