import { NextResponse } from "next/server";
import { getCourseDetail } from "@/content/courses";

/**
 * Downloadable interview question bank per track: a self-contained, print-
 * ready HTML file (students can Save as PDF) combining the kimi-k3 question
 * bank, rising/cooling skill demand, and the track's market-demand snapshot.
 * Data comes from the sibling API routes (shared hourly caches), so this
 * stays consistent with what the page shows.
 */

type QRound = { round: number; name: string; questions: string[] };
type Signal = { skill: string; change: string; note: string };

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export async function GET(req: Request, ctx: { params: Promise<{ slug: string }> }) {
  const { slug } = await ctx.params;
  const course = getCourseDetail(slug);
  if (!course || !course.live) return NextResponse.json({ error: "unknown course" }, { status: 404 });

  const origin = new URL(req.url).origin;
  const [qb, ms, jd] = await Promise.all([
    fetch(`${origin}/api/interview-questions`).then((r) => r.json()).catch(() => null),
    fetch(`${origin}/api/market-signals`).then((r) => r.json()).catch(() => null),
    fetch(`${origin}/api/job-demand`).then((r) => r.json()).catch(() => null),
  ]);

  const rounds: QRound[] = qb?.tracks?.[slug] ?? [];
  const rising: Signal[] = ms?.rising ?? [];
  const cooling: Signal[] = ms?.cooling ?? [];
  const demand = jd?.tracks?.[slug];
  const live = qb?.source === "kimi-k3";
  const date = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${esc(course.name)} — Interview Question Bank · BrowseJobs</title>
<style>
  * { box-sizing: border-box; margin: 0; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; color: #0a1220; padding: 48px 40px; max-width: 820px; margin: 0 auto; }
  .kicker { font-size: 11px; letter-spacing: 3px; text-transform: uppercase; color: #1b6df0; font-weight: 700; }
  h1 { font-size: 34px; letter-spacing: -0.5px; margin-top: 8px; }
  .meta { color: #5a6b85; font-size: 13px; margin-top: 6px; }
  .badge { display: inline-block; background: ${live ? "#e6f7ef" : "#eef2f8"}; color: ${live ? "#0ba860" : "#5a6b85"}; font-size: 11px; font-weight: 700; border-radius: 99px; padding: 3px 10px; margin-top: 10px; }
  h2 { font-size: 20px; margin: 36px 0 12px; border-bottom: 2px solid #e7f1fe; padding-bottom: 6px; }
  .round { margin: 18px 0; }
  .round h3 { font-size: 15px; color: #0e3fa9; }
  ol { margin: 8px 0 0 20px; }
  li { margin: 6px 0; font-size: 14px; line-height: 1.5; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
  th, td { text-align: left; padding: 7px 10px; border-bottom: 1px solid #e8edf5; }
  th { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #5a6b85; }
  .up { color: #0ba860; font-weight: 700; } .down { color: #b45309; font-weight: 700; }
  .note { font-size: 12px; color: #5a6b85; margin-top: 6px; }
  .cta { margin-top: 40px; background: #0a1220; color: #fff; border-radius: 14px; padding: 22px; }
  .cta a { color: #7db4ff; font-weight: 700; text-decoration: none; }
  .foot { margin-top: 26px; font-size: 11px; color: #8a97ab; line-height: 1.6; }
  @media print { body { padding: 24px; } .cta a { color: #7db4ff; } }
</style>
</head>
<body>
  <p class="kicker">BrowseJobs · Interview Question Bank</p>
  <h1>${esc(course.name)}</h1>
  <p class="meta">${esc(course.tagline)} · Generated ${date}</p>
  <span class="badge">${live ? "● Generated by the BrowseJobs engine (kimi-k3)" : "Curated edition"}</span>

  <h2>What interviews ask, round by round</h2>
  ${rounds
    .map(
      (r) => `<div class="round"><h3>Round ${r.round} · ${esc(r.name)}</h3><ol>${r.questions
        .map((q) => `<li>${esc(q)}</li>`)
        .join("")}</ol></div>`,
    )
    .join("") || "<p class='note'>Question bank is being refreshed — check back shortly.</p>"}

  ${demand ? `
  <h2>Market demand for this track</h2>
  <p style="font-size:15px"><b>≈ ${demand.total.toLocaleString("en-IN")}</b> active openings in India (last 30 days, est.) · trend <span class="up">${esc(demand.trend)}</span></p>
  <table>
    <tr><th>Role</th><th>Est. openings</th></tr>
    ${demand.roles.map((r: { role: string; count: number }) => `<tr><td>${esc(r.role)}</td><td>≈ ${r.count.toLocaleString("en-IN")}</td></tr>`).join("")}
  </table>
  <p class="note">Portal mix: ${demand.portals.map((p: { name: string; share: number }) => `${esc(p.name)} ${p.share}%`).join(" · ")}. Verify any of this yourself — open Naukri, search the role, filter “Last 7 days”, count.</p>
  ` : ""}

  ${rising.length ? `
  <h2>Skills heating up ▲ / cooling down ▼</h2>
  <table>
    <tr><th>Skill</th><th>Demand</th><th>Why</th></tr>
    ${rising.map((s) => `<tr><td>${esc(s.skill)}</td><td class="up">▲ ${esc(s.change)}</td><td>${esc(s.note)}</td></tr>`).join("")}
    ${cooling.map((s) => `<tr><td>${esc(s.skill)}</td><td class="down">▼ ${esc(s.change)}</td><td>${esc(s.note)}</td></tr>`).join("")}
  </table>
  ` : ""}

  <div class="cta">
    <b>Want the answers drilled into you?</b><br/>
    The ${esc(course.name)} syllabus is rebuilt monthly from questions exactly like these.
    Start with three free steps — counselling, a live masterclass and a 7-hour bootcamp — before paying a rupee.<br/><br/>
    <a href="https://browsejobs.ai/courses/${esc(course.slug)}">browsejobs.ai/courses/${esc(course.slug)}</a>
  </div>

  <p class="foot">
    Market figures are directional estimates generated by BrowseJobs' AI market analysis — signals, not guarantees.
    We publish how to verify every claim (open Naukri and count). Questions are compiled from our monthly analysis of real
    interview loops in Indian tech hiring. © BrowseJobs. Tip: use your browser's Print → Save as PDF for a print copy.
  </p>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "content-disposition": `attachment; filename="browsejobs-${slug}-question-bank.html"`,
      "cache-control": "no-store",
    },
  });
}
